### ISSUE TITLE
Interaction of import list and hiding lists

### ISSUE THREAD

**Issue by fendor** [dan-t/hsimport#19]
Currently, if we execute the following
```bash
> hsimport --hiding -m Data.Text -s isInfixOf Main.hs
```
on a file 
```haskell
import Data.Text (isInfixOf, isPrefixOf)

main = return ()
```
it results in:

```haskell
import Data.Text (isInfixOf, isPrefixOf)
import Data.Text hiding (isInfixOf)

main = return ()
```

I would suggest, that it tries to be a little smarter, e.g. in this case, it should result in:

```haskell
import Data.Text (isPrefixOf)

main = return ()
```

I imagine, the changed behaviour would increase the code complexity, but I think it makes a lot of sense.
If this is the better behaviour, I would be happy to provide a pr for it!

**Comment by dan-t** [comment]
I’m not quite sure if that’s the right behaviour for hsimport.

I can understand your reasoning, but is it the expected output
for the user? Perhaps he isn’t aware of the already available import
and therefore outputing an error and displaying the contradiction
might be the better option.

A file could e.g. also only contain a ‘import qualified Data.Text as T’,
in which case a symbol hiding would have no effect, or it could have a
‘import Data.Text’, in which case any symbol import would have no effect.

So I’m not sure how much smartness would be good for the user.
I’ve to think a bit about it.

**Comment by fendor** [comment]
I agree and fully understand your reasoning. I am also not sure how smart this should be since there are a lot of corner cases that would need discussion, and do not have a clear course of action.

**Comment by dan-t** [comment]
There's currently already some kind of smartness for inputs like:

    import Data.Text

    main = return ()

Calling `hsimport -m Data.Text -s isInfixOf` won't change anything,
because all symbols of `Data.Text` are already imported.


Also for an input like:

    import Data.Text (isPrefixOf)

    main = return ()

Calling `hsimport -m Data.Text -s isInfixOf` won't add a new import,
but change the available one to `import Data.Text (isPrefixOf, isInfixOf)`.


So considering this, your suggestion seems to fit nicely, that `--hiding`
might remove a symbol from an available import.


Following a few examples of IMHO also sensible import changes. Each
example contains just one input import I), the hsimport command C) and
the change to the input import O).

I) import Data.Text
C) hsimport -m Data.Text --hiding -s isInfixOf
O) import Data.Text hiding (isInfixOf)

I) import Data.Text (isPrefixOf)
C) hsimport -m Data.Text --hiding -s isInfixOf
O) import Data.Text hiding (isInfixOf)

I) import Data.Text hiding (isPrefixOf)
C) hsimport -m Data.Text -s isPrefixOf
O) import Data.Text

**Comment by fendor** [comment]
What shall happen in the case of non-sensical import lines, such as:
```haskell
import Data.Text (isPrefixOf)
import Data.Text hiding (isInfixOf)
```
```bash
> hsimport --hiding -m Data.Text -s isPrefixOf Main.hs
```

Admittedly, this doesnt make sense, but what should happen in that case? I would say, just adding it to the hiding import statement makes the most sense.

**Comment by dan-t** [comment]
On Tue, Jun 04, 2019 at 04:39:45AM -0700, fendor wrote:
> What shall happen in the case of non-sensical import lines, such as:
> 
> import Data.Text (isPrefixOf)
> import Data.Text hiding (isInfixOf)
> 
> > hsimport --hiding -m Data.Text -s isPrefixOf Main.hs
> 
> Admittedly, this doesnt make sense, but what should happen in that case? I would say, just adding it to the hiding
> import statement makes the most sense.

Removing the first import and adding it to the second would be the
nicest solution, but this might complicate the code quite a bit
for a most likely very rare case.

So just adding it to the second import seems ok.

I'm wondering if there should be some kind of normalize operation
that can clean up such cases.

The imported symbols from the above example are all but `isInfixOf`,
so the normalize operation would reduce it to just `import Data.Text hiding (isInfixOf)`.

But for now just implement your suggested solution and I might have
a look at the normalize operation.

**Comment by dan-t** [comment]
Thinking a bit further about the whole issue, there’s no way to handle all possible cases correctly, or even knowing what the user considers as correct.

So I would suggest to keep it simple and only search for an already available ‘hiding’ import
and extend it, and otherwise just add a new hiding import.
